name: Action Checkout Example
on:
  schedule:
    cron: "* * * * *"
  #push:
  pull_request:
    types: [closed,assigned,reopened,opened]
jobs:
  Shell_Commands:
    runs-on: ubuntu-latest
    steps:
      - name: Shell_commands
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ GITHUB.TOKEN }}"
      - name: Check out Actions
        uses: actions/checkout@v1
      - name:
        run: |
          pwd
          ls
      - name: JS Actions
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with: 
          who-to-greet: Balaji
      - name: Greet Time
        run: echo "${{steps.greet.outputs.time}}"



